security:
  user:
    name: buzz
    password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
      
#logging:
#  level:
#    org.springframework.data.rest: debug

spring:
  data:
    rest:
      base-path: /api

---
spring:
  profiles: prod
  
  datasource:
    url: "jdbc:mysql://localhost:3306/tacocloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false"
    username: root
    password: 1234
    
logging:
  level:
    tacos: WARN
    
